version: "3.9"

services:
  web:
    build: .
    container_name: wllnesstrack
    ports:
      - "8011:8011"
    volumes:
      - .:/home/user/app
    env_file:
      - .env
    environment:
      ENV: production
    command: uvicorn main:app --host 0.0.0.0 --port 8011 --reload
